[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Trom_functions.x",
    "-C", "force-frame-pointers",
]

[build]
target = "riscv32imc-unknown-none-elf"

[profile.release]
debug = false
lto = true
opt-level = "s"
incremental = false
codegen-units = 1

[profile.dev.package.esp-wifi]
opt-level = 3

[unstable]
build-std = [ "core" ]